-- ================================
-- AMB MTA:SA - Defines
-- All constants and definitions
-- ================================

-- Player constants
MAX_PLAYERS = 100
MAX_VEHICLES = 2000
INVALID_PLAYER_ID = -1

-- Colors
COLOR_WHITE = "#FFFFFF"
COLOR_RED = "#FF0000"
COLOR_GREEN = "#00FF00"
COLOR_BLUE = "#0000FF"
COLOR_YELLOW = "#FFFF00"
COLOR_ORANGE = "#FFA500"
COLOR_PURPLE = "#800080"
COLOR_GREY = "#808080"
COLOR_GRAD1 = "#B4B5B7"
COLOR_GRAD2 = "#BFC0C2"
COLOR_GRAD3 = "#CBCCCE"
COLOR_GRAD4 = "#D6D7D9"
COLOR_GRAD5 = "#E1E2E4"
COLOR_GRAD6 = "#ECECEC"

-- Money constants
STARTING_MONEY = 5000
MAX_MONEY = 999999999

-- Vehicle constants
VEHICLE_LOCK_NONE = 0
VEHICLE_LOCK_LOCKED = 1
VEHICLE_LOCK_HOTWIRED = 2

-- Admin levels table for easy access
ADMIN_LEVELS = {
    PLAYER = 0,
    HELPER = 1,
    MODERATOR = 2,
    ADMIN = 3,
    SENIORADMIN = 4,
    HEADADMIN = 5,
    MANAGER = 6,
    DEVELOPER = 7,
    FOUNDER = 8,
    GOD = 99999
}

-- Dialog IDs
DIALOG_REGISTER = 1
DIALOG_LOGIN = 2
DIALOG_STATS = 3
DIALOG_PHONE = 4
DIALOG_BANK = 5
DIALOG_VEHICLE_BUY = 6
DIALOG_BUSINESS = 7
DIALOG_PROPERTY = 8
DIALOG_JOB = 9
DIALOG_FAMILY = 10

-- Job IDs
JOB_NONE = 0
JOB_POLICE = 1
JOB_MEDIC = 2
JOB_TAXI = 3
JOB_TRUCKER = 4
JOB_MECHANIC = 5

-- Faction IDs
FACTION_NONE = 0
FACTION_POLICE = 1
FACTION_FBI = 2
FACTION_ARMY = 3
FACTION_MEDIC = 4
FACTION_GANG = 5

-- Interior IDs
INTERIOR_NONE = 0
INTERIOR_HOUSE = 1
INTERIOR_BUSINESS = 2
INTERIOR_BANK = 3

-- Feature flags
FEATURE_PHONE_ENABLED = true
FEATURE_BANK_ENABLED = true
FEATURE_VEHICLE_DEALERSHIP = true
FEATURE_PROPERTIES = true
FEATURE_JOBS = true
FEATURE_FAMILIES = true

print("📝 Defines loaded")
